#!/usr/bin/env perl
#
# Programmer:    Craig Stuart Sapp <craig.stanford.edu>
# Creation Date: Sat Oct 28 21:52:06 PDT 2023
# Last Modified: Sat Oct 28 21:52:12 PDT 2023
# Filename:      jrp-scores/bin/getEncodingDate
# Syntax:        perl 5
#
# Description:   Extract encoding date from scores (END reference record).
#                Input is a list of work IDs:
#
#		Ano1001a
#		Ano1001b
#		Ano1001c
#		Ano1001d
#		Ano1001e
#		Ano1002
#		Ano1025a
#		Ano1025b
#		Ano1025c
#		Ano1025d
#                 This is copyied from the spreadsheet
#                 https://bit.ly/jrp-metadata, column A.
#

use strict;
use Getopt::Long;

my $prefixIds = 0;
Getopt::Long::Configure("bundling");
GetOptions (
   'p|prefix-ids' => \$prefixIds
);

my @list = <>;
chomp @list;

if (@list < 100) {
	die "Usage: getWorkIdList | $0 | pbcopy\n";
}

foreach my $entry (@list) {
	if ($entry !~ /^([A-Z][a-z][a-z])\d{4}/) {
		print "$entry\t" if $prefixIds;
		print "\n";
		next;
	}
	my $composer = $1;
		
	my $pattern = "$composer/kern/$entry-*\.krn";
	my @files = glob($pattern);

	if (@files == 0) {
		print "$entry\tNO_FILE" if $prefixIds;
		print "\n";
		next;
	}
	if (@files > 1) {
		die "Error: duplicate IDs in files: ", join("\t", @files), "\n";
	}
	my $END = "";
	my @contents;
	open(FILE, $files[0]) or $END = "NO_FILE";
	@contents = <FILE>;
	close FILE;
	foreach my $line (@contents) {
		next if $line !~ /^!!!END:/;
		chomp $line;
		if ($line =~ /^!!!END:\s*(.*)\s*$/) {
			my $value = $1;
			if ($value !~ /^\s*$/) {
				$END = $value;
				last;
			}
		}
	}
	$END =~ s/\/$//;

	print "$entry\t" if $prefixIds;
	print "$END\n";
}

	



