#!/usr/bin/env perl
#
# Programmer:    Craig Stuart Sapp <craig.stanford.edu>
# Creation Date: Sat Oct  7 02:08:07 PDT 2023
# Last Modified: Sun Oct 29 08:30:33 PDT 2023
# Filename:      jrp-scores/bin/getFilename
# Syntax:        perl 5
#
# Description:   Extract filenames for files according to the input
#                file which contains a single ID for each file on
#                each line, such as:
#		Ano1001a
#		Ano1001b
#		Ano1001c
#		Ano1001d
#		Ano1001e
#		Ano1002
#		Ano1025a
#		Ano1025b
#		Ano1025c
#		Ano1025d
#                 This is copyied from the spreadsheet
#                 https://bit.ly/jrp-metadata, column A and stored
#                 into a file call jrp-scores/ids.txt Then the output
#                 of this program is pasted into the "Filename"
#                 column of the same spreadsheet.
#

use strict;
use Getopt::Long;

my $prefixIds = 0;
Getopt::Long::Configure("bundling");
GetOptions (
   'p|prefix-ids' => \$prefixIds
);

my @list = <>;
chomp @list;
s/\r$// for @list;

if (!@list) {
	die "Usage: getWorkIdList | $0 | pbcopy\n";
}

foreach my $entry (@list) {
	if ($entry !~ /^([A-Z][a-z][a-z])\d{4}[A-Za-z0-9]*(?:\.[A-Za-z0-9]+)*$/) {
		die "Invalid work ID: $entry\n" if $entry ne "";
		print "$entry\t" if $prefixIds;
		print "\n";
		next;
	}
	my $composer = substr($entry, 0, 3);
		
	my @files = glob("$composer/$entry-*\.krn");

	if (@files == 0) {
		print "$entry\t" if $prefixIds;
		print "NO_FILE\n";
		next;
	}
	if (@files > 1) {
		die "Error: duplicate IDs in files: ", join("\t", @files), "\n";
	}
	my $base = $files[0];
	$base =~ s/.*\///;
	print "$entry\t" if $prefixIds;
	print "$base\n";
}

	

