#!/usr/bin/env perl
#
# Programmer:    Craig Stuart Sapp <craig.stanford.edu>
# Creation Date: Sat Oct  7 02:03:41 PDT 2023
# Last Modified: Sat Feb 17 11:49:59 PST 2024
# Filename:      jrp-scores/bin/getNoteCount
# Syntax:        perl 5
#
# Description:   Extract notecounts for files according to the input
#                file which contains a single ID for each file on
#                each line, such as:
#		Ano1001a
#		Ano1001b
#		Ano1001c
#		Ano1001d
#		Ano1001e
#		Ano1002
#		Ano1025a
#		Ano1025b
#		Ano1025c
#		Ano1025d
#
#                This is copyied from the spreadsheet
#                https://bit.ly/jrp-metadata, column A.  Then the
#                output of this program is pasted into the "Notes"
#                column of the same spreadsheet.

use strict;

my $notecount = `which notecount`;
chomp $notecount;
die "Install Humdrum Extras for notecount command\n" if $notecount =~ /^s\*$/;

my @list = glob("[A-Z][a-z][a-z]/kern/*.krn");
chomp @list;

if (@list < 40) {
	die "Problem finding files to count notes\n";
}

my $sum = 0;
my $filecount = 0;
my %id;
foreach my $file (@list) {
	my $filebase = $file;
	$filebase =~ s/.*\///;
	if ($filebase !~ /^([A-Z][a-z][a-z])\d{4}/) {
		print "Incorrect filename: $file\n";
		next;
	}
	my $composer = $1;
	my $fileid = "";
	if ($filebase !~ /^([A-z][a-z][a-z]\d{4}.*?)-/) {
		print "Error searching for ID in filename: $filebase\n";
		next;
	}
	$fileid = $1;

	my $command = "$notecount -s \"$file\" | cut -f 1";
	my $result = `$command`;
	chomp $result;
	$filecount++;
	if ($result =~ /^\d+$/) {
		$sum += $result;
	} else {
		print "Error counting notes in $file\n";
	}
}

print "$sum notes in $filecount files\n";



