#!/usr/bin/env perl
#
# Programmer:    Craig Stuart Sapp <craig.stanford.edu>
# Creation Date: Sat Oct  7 02:03:41 PDT 2023
# Last Modified: Sat Feb 17 11:49:59 PST 2024
# Filename:      jrp-scores/bin/getNoteCount
# Syntax:        perl 5
#
# Description:   Extract notecounts for files according to the input
#                file which contains a single ID for each file on
#                each line, such as:
#		Ano1001a
#		Ano1001b
#		Ano1001c
#		Ano1001d
#		Ano1001e
#		Ano1002
#		Ano1025a
#		Ano1025b
#		Ano1025c
#		Ano1025d
#
#                This is copyied from the spreadsheet
#                https://bit.ly/jrp-metadata, column A.  Then the
#                output of this program is pasted into the "Notes"
#                column of the same spreadsheet.

use strict;
use Getopt::Long;

my $composerQ = 0;
my $globalQ   = 0;

Getopt::Long::Configure("bundling");
GetOptions (
   'c|composer' => \$composerQ,
   'g|global'   => \$globalQ
);

my $notecount = `which notecount`;
chomp $notecount;
die "Install Humdrum Extras for notecount command\n" if $notecount eq "";

if ($composerQ) {
	countByComposer();
}
elsif ($globalQ) {
	countAllFiles();
}
else {
	countByWorkId();
}

exit(0);

###########################################################

sub countByWorkId {

	my @list = <>;
	chomp @list;

	if (@list < 10) {
		die "Usage: getWorkIdList | getNoteCount\n";
	}

	foreach my $entry (@list) {

		next if $entry !~ /^([A-Z][a-z][a-z])/;
		my $composer = $1;

		my @files = glob("$composer/kern/$entry-*.krn");

		if (@files == 0) {
			print "$entry\tNO_FILE\n";
			next;
		}

		my $sum = 0;

		foreach my $file (@files) {
			my $result = `$notecount -s "$file" | cut -f 1`;
			chomp $result;
			$sum += $result if $result =~ /^\d+$/;
		}

		print "$sum\n";
	}
}

###########################################################

sub countByComposer {

	my @list = sort glob("[A-Z][a-z][a-z]/kern");

	foreach my $cdir (@list) {

		next unless $cdir =~ /^([A-Z][a-z][a-z])/;
		my $composer = $1;

		my @files = glob("$cdir/*.krn");

		my $sum = 0;
		my $filecount = 0;

		foreach my $file (@files) {
			my $result = `$notecount -s "$file" | cut -f 1`;
			chomp $result;
			$sum += $result if $result =~ /^\d+$/;
			$filecount++;
		}

		print "$composer\t$sum\t$filecount\n";
	}
}

###########################################################

sub countAllFiles {

	my @list = glob("[A-Z][a-z][a-z]/kern/*.krn");

	my $sum = 0;
	my $filecount = 0;

	foreach my $file (@list) {
		my $result = `$notecount -s "$file" | cut -f 1`;
		chomp $result;
		$sum += $result if $result =~ /^\d+$/;
		$filecount++;
	}

	print "$sum notes in $filecount files\n";
}