#!/usr/bin/env perl
#
# Programmer:    Craig Stuart Sapp <craig.stanford.edu>
# Creation Date: Sat Oct  7 02:03:41 PDT 2023
# Last Modified: Sat Feb 17 11:49:59 PST 2024
# Filename:      jrp-scores/bin/getNoteCount
# Syntax:        perl 5
#
# Description:   Extract notecounts for files according to the input
#                file which contains a single ID for each file on
#                each line, such as:
#		Ano1001a
#		Ano1001b
#		Ano1001c
#		Ano1001d
#		Ano1001e
#		Ano1002
#		Ano1025a
#		Ano1025b
#		Ano1025c
#		Ano1025d
#
#                This is copyied from the spreadsheet
#                https://bit.ly/jrp-metadata, column A.  Then the
#                output of this program is pasted into the "Notes"
#                column of the same spreadsheet.

use strict;
use Getopt::Long;

my $composerQ = 0;
my $globalQ   = 0;

Getopt::Long::Configure("bundling");
GetOptions (
   'c|composer' => \$composerQ,
   'g|global'   => \$globalQ
);

my $notecount = `which notecount`;
chomp $notecount;
die "Install Humdrum Extras for notecount command\n" if $notecount eq "";

if ($composerQ) {
	countByComposer();
}
elsif ($globalQ) {
	countAllFiles();
}
else {
	countByWorkId();
}

exit(0);

###########################################################

sub countByWorkId {

	my @list = <>;
	chomp @list;
	s/\r$// for @list;

	if (!@list) {
		die "Usage: getWorkIdList | getNoteCount\n";
	}

	foreach my $entry (@list) {

		if ($entry eq "") { print "\n"; next; }
		die "Invalid work ID: $entry\n" unless $entry =~ /^[A-Z][a-z]{2}\d{4}[A-Za-z0-9]*(?:\.[A-Za-z0-9]+)*$/;
		my $composer = substr($entry, 0, 3);

		my @files = glob("$composer/$entry-*.krn");

		if (@files == 0) {
			print "NO_FILE\n";
			next;
		}

		die "Error: duplicate IDs in files: @files\n" if @files > 1;
		my $sum = 0;

		foreach my $file (@files) {
			$sum += readNoteCount($file);
		}

		print "$sum\n";
	}
}

###########################################################

sub countByComposer {

	my @list = sort glob("[A-Z][a-z][a-z]");

	foreach my $cdir (@list) {

		next unless $cdir =~ /^([A-Z][a-z][a-z])/;
		my $composer = $1;

		my @files = glob("$cdir/*.krn");

		my $sum = 0;
		my $filecount = 0;

		foreach my $file (@files) {
			$sum += readNoteCount($file);
			$filecount++;
		}

		print "$composer\t$sum\t$filecount\n";
	}
}

###########################################################

sub countAllFiles {

	my @list = glob("[A-Z][a-z][a-z]/*.krn");

	my $sum = 0;
	my $filecount = 0;

	foreach my $file (@list) {
		$sum += readNoteCount($file);
		$filecount++;
	}

	print "$sum notes in $filecount files\n";
}

# List-form execution safely handles apostrophes and other filename characters.
sub readNoteCount {
	my ($file) = @_;
	open(my $pipe, "-|", $notecount, "-s", $file)
		or die "Cannot run notecount: $!\n";
	local $/;
	my $result = <$pipe>;
	close($pipe) or die "notecount failed for $file\n";
	die "Invalid note count for $file\n"
		unless defined($result) && $result =~ /\A(\d+)(?:\t[^\r\n]*)?\r?\n?\z/;
	return $1;
}
