#!/usr/bin/env perl
#
# Programmer:    Craig Stuart Sapp <craig.stanford.edu>
# Creation Date: Sat Oct 28 14:31:11 PDT 2023
# Last Modified: Sat Oct 28 14:31:14 PDT 2023
# Filename:      jrp-scores/bin/getWorkIdList
# Syntax:        perl 5
#
# Description:   Download work IDs for files from JRP metadata spreadsheet, such as:
#
#		Ano1001a
#		Ano1001b
#		Ano1001c
#		Ano1001d
#		Ano1001e
#		Ano1002
#		Ano1025a
#		Ano1025b
#		Ano1025c
#		Ano1025d
#                 This is copyied from the spreadsheet
#                 https://bit.ly/jrp-metadata, column A.
#

use strict;
use warnings;
use JSON::PP qw(decode_json);
use Getopt::Long;

# Override this deployment with JRP_METADATA_SID when the web app changes.
my $sid = $ENV{JRP_METADATA_SID} || "AKfycbxcZCQAja8UuLu0z-LtHN0B0gmzX56nKw253sXofw1uD81Yn00DIzSnZuoWK1RfUmBdBg";
my $input;
GetOptions("input=s" => \$input) or die "Usage: $0 [--input works.json]\n";
die "Unexpected arguments\n" if @ARGV;
my $json;
{
	local $/;
	if (defined $input) {
		open(my $file, "<", $input) or die "Cannot read $input: $!\n";
		$json = <$file>;
		close($file);
	} else {
		die "Invalid deployment ID\n" unless $sid =~ /^[A-Za-z0-9_-]+$/;
		my $url = "https://script.google.com/macros/s/$sid/exec?sheet=works";
		open(my $pipe, "-|", "curl", "--fail", "--silent", "--show-error",
			"--location", "--connect-timeout", "15", "--max-time", "90", $url)
			or die "Cannot run curl: $!\n";
		$json = <$pipe>;
		close($pipe) or die "Works download failed; no IDs generated.\n";
	}
}
my $rows = eval { decode_json($json // "") };
die "Works feed is not valid JSON; no IDs generated.\n" if $@;
die "Works feed must be a nonempty array.\n" unless ref($rows) eq "ARRAY" && @$rows;
my @ids;
my $found = 0;
for my $row (@$rows) {
	die "Invalid Works row.\n" unless ref($row) eq "HASH";
	my $id = $row->{WORK_ID} // "";
	die "Invalid WORK_ID in Works feed.\n" if ref($id) || ($id ne "" && $id !~ /^[A-Z][a-z]{2}\d{4}[A-Za-z0-9]*(?:\.[A-Za-z0-9]+)*$/);
	$found++ if $id ne "";
	push @ids, $id;
}
die "Works feed contains no work IDs.\n" unless $found;
# Preserve input order and blank rows; never emit part of an invalid response.
print join("\n", @ids), "\n";
